### ISSUE TITLE
Retrying data read: invalid literal for int() with base 16

### ISSUE THREAD

**Issue by bmangaming** [JK-Rolling/DuinoCoinUSBI2C_Adaptor#1]
Keep getting the following error when running with a single slave (using Uno v3 for both master and slave, wired as per diagram provided with this project. Slave is running DuinoCoin_RPI_Tiny_Slave). py script running on Windows 11

16:40:38.348661 DEBUG: 1: Requesting job
16:40:38.626209 DEBUG: 1: Received: 7bd743d94cdbe592b28f5b3515760662ad8e49f2
16:40:38.627209 DEBUG: 1: Sending job to the board
16:40:38.627709 DEBUG: 1: Job+crc8: 7bd743d94cdbe592b28f5b3515760662ad8e49f2,1bc917db03702599ace7ca391fd1bd362b36aa91,6,12

16:40:41.325177 DEBUG: 1: Reading result from the board
**16:40:51.339915 DEBUG: 1: Retrying data read: invalid literal for int() with base 16: ''**

**Comment by JK-Rolling** [comment]
seems like the data return is empty. I've just tested it and seems to be working fine. is this still reproducible?
